In [0]:
import os
import sys

import numpy as np
import pandas as pd

In [16]:
!pip install pyqubo

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


上の指示に従って、キーを入力してください

ディレクトリが正しいか下cellで確認してください。  
1.wrapper.pyが存在する。  
2.入力データ用csvが存在する

In [18]:
# check directory. 
path = "./drive/My Drive/human_affairs"

os.listdir(path)

['test1.csv', 'wrapper.py', 'UseMe.ipynb', '__pycache__', 'test', 'test2']

In [0]:
# add wrapper.py directory
sys.path.append(path)

In [0]:
import wrapper

↑環境設定終了
↓データ入力

In [0]:
# 名簿データcsvを入れてください。
# 名前の列名は"name" , 所属の列名は "group" としてください。
df = pd.read_csv(f"{path}/test1.csv")

In [22]:
member_num = df.shape[0]
print(f"人数は{member_num}")

人数は31


In [0]:
# 部署数設定。
department_num = 8
department_names = [f"D{i}" for i in range(department_num)]

In [0]:
# ターム数設定。
term_num = department_num
term_names = [f"T{i}" for i in range(term_num)]

In [25]:
# 所属ごとに配属される部署・ターム (region)を指定できます。

np_all = np.ones((department_num,term_num))
np_rest = np.eye(term_num)

# 所属数分regionの設定をしてください。
# ↓サンプルで所属が２の場合
np_A = np.zeros((department_num,term_num))
np_A[[2,3],0:2] = 1
np_A[[4,5],2:4] = 1
np_A[[6,7],4:6] = 1
np_A[[0,1],6:8] = 1
np_B = np_all - np_rest - np_A

region_dict = {}
region_dict["A"] = np_A
region_dict["B"] = np_B

# 設定したregionの表示
for key,value in region_dict.items():
  print("グループ："+key)
  print(value,end="\n\n")

グループ：A
[[0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]]

グループ：B
[[0. 1. 1. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1.]
 [1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 0. 0. 1. 0.]]



↑データ入力
↓配属プログラムを作る

In [26]:
# 最適化の後に、よい結果を save_folderに出力。
save_folder = "test"
WOpt = wrapper.Opt(df,department_names,term_names,region_dict,path+"/"+save_folder)

capacity is estimated below
A
[[-2. -2. -2. -2. -2. -2.  5.  5.]
 [-2. -2. -2. -2. -2. -2.  5.  5.]
 [ 5.  5. -2. -2. -2. -2. -2. -2.]
 [ 5.  5. -2. -2. -2. -2. -2. -2.]
 [-2. -2.  5.  5. -2. -2. -2. -2.]
 [-2. -2.  5.  5. -2. -2. -2. -2.]
 [-2. -2. -2. -2.  5.  5. -2. -2.]
 [-2. -2. -2. -2.  5.  5. -2. -2.]]

B
[[-2.   4.2  4.2  4.2  4.2  4.2 -2.  -2. ]
 [ 4.2 -2.   4.2  4.2  4.2  4.2 -2.  -2. ]
 [-2.  -2.  -2.   4.2  4.2  4.2  4.2  4.2]
 [-2.  -2.   4.2 -2.   4.2  4.2  4.2  4.2]
 [ 4.2  4.2 -2.  -2.  -2.   4.2  4.2  4.2]
 [ 4.2  4.2 -2.  -2.   4.2 -2.   4.2  4.2]
 [ 4.2  4.2  4.2  4.2 -2.  -2.  -2.   4.2]
 [ 4.2  4.2  4.2  4.2 -2.  -2.   4.2 -2. ]]

start trial
1 {'A': 704, 'B': 622} {'A': 6, 'B': 6}
2 {'A': 768, 'B': 576} {'A': 8, 'B': 5}
3 {'A': 704, 'B': 590} {'A': 6, 'B': 6}
4 {'A': 800, 'B': 612} {'A': 8, 'B': 5}
5 {'A': 928, 'B': 566} {'A': 8, 'B': 4}
6 {'A': 736, 'B': 640} {'A': 6, 'B': 6}
7 {'A': 768, 'B': 580} {'A': 8, 'B': 4}
8 {'A': 736, 'B': 578} {'A': 8, 'B': 5}
9 {'A': 

指定したフォルダーに結果一式が出力されています。
google driveは反映が少し遅いので、１分程待つ必要があるかもしれません。

In [27]:
# 気に入らない場合の再チャレンジ
save_folder = "test2"

WOpt.challenge()
WOpt.save_result(folder_path=path+"/"+save_folder)

start trial
1 {'A': 832, 'B': 620} {'A': 8, 'B': 5}
2 {'A': 736, 'B': 572} {'A': 8, 'B': 4}
3 {'A': 768, 'B': 650} {'A': 8, 'B': 5}
4 {'A': 736, 'B': 594} {'A': 8, 'B': 5}
5 {'A': 800, 'B': 578} {'A': 8, 'B': 5}
6 {'A': 736, 'B': 574} {'A': 8, 'B': 4}
7 {'A': 736, 'B': 606} {'A': 8, 'B': 5}
8 {'A': 960, 'B': 590} {'A': 8, 'B': 4}
9 {'A': 736, 'B': 630} {'A': 8, 'B': 5}
10 {'A': 736, 'B': 558} {'A': 8, 'B': 4}
11 {'A': 736, 'B': 614} {'A': 8, 'B': 5}
12 {'A': 768, 'B': 634} {'A': 8, 'B': 5}
13 {'A': 736, 'B': 604} {'A': 8, 'B': 5}
14 {'A': 800, 'B': 582} {'A': 8, 'B': 5}
15 {'A': 768, 'B': 588} {'A': 8, 'B': 5}
16 {'A': 736, 'B': 582} {'A': 8, 'B': 5}
17 {'A': 736, 'B': 614} {'A': 8, 'B': 5}
18 {'A': 736, 'B': 584} {'A': 8, 'B': 5}
19 {'A': 704, 'B': 570} {'A': 8, 'B': 4}
20 {'A': 704, 'B': 542} {'A': 6, 'B': 4}
